### ISSUE TITLE
你好大佬，怎么添加css-loader

### ISSUE THREAD

**Issue by YinRenjie1993** [LANIF-UI/dva-boot-admin#1]
你好大佬，怎么添加css-loader，让less可以像roadlog一样引用，比如import styles from './index.less'
  className={styles.test}

**Comment by weiq** [comment]
脚手架底层是create-react-app,使用的[react-app-rewired](https://github.com/timarney/react-app-rewired#loaders)进行个性化定制，你是想加一个css-modules吧，只要把现有的*.less写成*.module.less就行了，具体见[react-app-rewire-less-modules](https://github.com/andriijas/react-app-rewire-less-modules),或者在react-app-rewired的loader里找其它的用用，但我不建议用css-modules，因为太麻烦，像这个工程里面这样写样式的话，其本也可以达到互不影响的目地。

**Comment by YinRenjie1993** [comment]
还有个问题我想把我的项目从roadhog转到这个脚手架上，但是start会内存溢出，roadhog确不会

**Comment by weiq** [comment]
没用过roadhog，内存溢出的话可能性太多了，我用这个脚手架也做过一些项目了没发现溢出情况

**Comment by YinRenjie1993** [comment]
![image](https://user-images.githubusercontent.com/11569655/39847372-d1c1259e-5433-11e8-83c9-8c8457ff4881.png)
![image](https://user-images.githubusercontent.com/11569655/39847383-e35a75f8-5433-11e8-983c-edd046a0f215.png)
![image](https://user-images.githubusercontent.com/11569655/39847400-fec05eac-5433-11e8-8097-cb8cc0b0ac5c.png)
大佬帮我看看我的mock写的有问题没

**Comment by weiq** [comment]
兄弟。你看一下这个工程下的例子吧，这里面也用到mock了， [config.js](https://github.com/LANIF-UI/dva-boot-admin/blob/8a182d0b40023e5ef0e71e8ebee5648342e39d6c/src/config.js#L11)里会为每个请求增加一个前缀,你这个mock加个前缀'/api/apicurrentuser' 或在config里把前缀去了

**Comment by YinRenjie1993** [comment]
我没用你的request，你看我截图的  抓包的请求的url和mock的url是一样的，不知道为啥不行 必须得用你的request吗

**Comment by weiq** [comment]
不知道你的项目改成什么样了，抱歉

**Comment by weiq** [comment]
暂时关闭了，有问题在开新贴吧
