### ISSUE TITLE
编译之后，总共45MB

### ISSUE THREAD

**Issue by spilledyear** [LANIF-UI/dva-boot-admin#102]
执行完 npm run build 之后， build文件夹45MB， 请问该怎么处理？ 看文档中写到打完包只有2MB

![buildDir](https://user-images.githubusercontent.com/24663965/92307703-d093c980-efca-11ea-8974-1e52c40ef4c2.png)

**Comment by weiq** [comment]
禁用sourcemap试试，2m是首屏打开浏览器需要加载的资源大小 https://github.com/LANIF-UI/dva-boot-admin/blob/master/docs/build.md#%E6%89%93%E5%8C%85%E4%BD%93%E7%A7%AF%E8%BF%87%E5%A4%A7--%E7%A6%81%E7%94%A8sourcemap
