### ISSUE TITLE
貌似少了个footer，有点不完美

### ISSUE THREAD

**Issue by win-hi** [LANIF-UI/dva-boot-admin#11]
貌似少了个footer，有点不完美

**Comment by weiq** [comment]
做成什么样的好呢，有什么好想法说说

**Comment by win-hi** [comment]
没啥想法，就是感觉网站一般都会有footer ，简单点 就行，比如
<Footer> 魏小雨荣誉出品 <a href="mailto:你的邮箱">你的邮箱</a> Version1.0.0 </Footer>
