### ISSUE TITLE
在childRoutes的组件里面再创建子路由

### ISSUE THREAD

**Issue by Montage-LSM** [LANIF-UI/dva-boot-admin#14]
你好，我想在childRoutes子路由里面，再创建一个，子路由，我是按照router/index.js里面写的。createRoutes，但提示我Each child in an array or iterator should have a unique "key" prop.
我看了一下是react-router里面需要一个唯一标识KEY。但是这个KEY不是已经封装好生成了么。能不能完善一个子路由的例子，比如，我想在列表中，对一条数据进行编辑，那肯定是要再从这个模块的里面跳转一层的。如何实现这个。

**Comment by weiq** [comment]
嗯好的，我会增加一个子路由的用法例子.

**Comment by weiq** [comment]
[多级路由写法](https://github.com/LANIF-UI/dva-boot-admin/tree/master/src/routes/Pages/LevelRoute)，示例在左侧菜单 > 页面 > 多级路由。

**Comment by Montage-LSM** [comment]
[原来如此，是在父节点里面单独存放了一下Switch，怪不得我之前一直不出来呢。我根据你这个稍微改进了一下。这样里面路由的内容就是独立的了。[http://7xpk4u.com1.z0.glb.clouddn.com/git-qa-1.png](url)

代码：
`
const { crud, loading, dispatch,routerData,location } = this.props;
//重点是这个location，根据location.name 获取到当前路由的值。
//然后根据子节点的进行判断。

    const {childRoutes} = routerData;
    // console.log("now.routers",location.pathname,childRoutes);
    let isJumpChild=false;
    childRoutes.map(item=>{
      if (location.pathname==item.key){
        isJumpChild=true;
        console.log("当前路由与子路由相匹配");
        return;
      }
    })
  if(isJumpChild){
return (<Switch>{childRoutes}</Switch>);
 }
else{
return (..父节点之前的那个Layout标签相关。)
}


`

**Comment by chenwangji** [comment]
项目预览里的二级路由跳转都会重定向到404，但是我看代码里已经注册了，是不是这样写还有点问题

**Comment by weiq** [comment]
@chenwangji https://lanif-ui.github.io/dva-boot-admin/#/dva-boot-admin/level-route/sub-route 请看一下这个示例，我本地和线上都是好使的

**Comment by chenwangji** [comment]
额 我看的就是你线上的，然后我本地跑也是那样，看代码应该不是要跳到 404 页面呀
![11111211](https://user-images.githubusercontent.com/23144765/53473470-7183f900-3aa5-11e9-9c8e-f6e0cbead0a8.png)
![222222](https://user-images.githubusercontent.com/23144765/53473475-747ee980-3aa5-11e9-9edc-916992046035.png)

**Comment by weiq** [comment]
@chenwangji 哦是标签模式么，你看一下提交历示，这个问题前一阵修复了

**Comment by weiq** [comment]
https://github.com/LANIF-UI/dva-boot-admin/commit/9b00dc05ef0a85ccbdd2344ed463e76b3d42f94d
https://github.com/LANIF-UI/dva-boot-admin/commit/9accaa596bdd086814c6bab3215ef84dd6345d7f

![333](https://user-images.githubusercontent.com/1697158/53473998-e6a3fe00-3aa6-11e9-93bb-db2c8ef32b7c.gif)
