### ISSUE TITLE
我用cnpm执行install正常，执行start就出错了

### ISSUE THREAD

**Issue by zxl78585** [LANIF-UI/dva-boot-admin#18]
cnpm版本:
cnpm@6.0.0 (/data/app/nodejs/node-v10.8.0-linux-x64/lib/node_modules/cnpm/lib/parse_argv.js)
npm@6.4.1 (/data/app/nodejs/node-v10.8.0-linux-x64/lib/node_modules/cnpm/node_modules/npm/lib/npm.js)
node@10.8.0 (/data/app/nodejs/node-v10.8.0-linux-x64/bin/node)
npminstall@3.11.0 (/data/app/nodejs/node-v10.8.0-linux-x64/lib/node_modules/cnpm/node_modules/npminstall/lib/index.js)
prefix=/data/app/nodejs/node-v10.8.0-linux-x64
linux x64 4.17.0-1.el7.elrepo.x86_64
registry=https://registry.npm.taobao.org
错误信息：
[root@centos dva-boot-admin]# cnpm run start

> dva-boot-admin@1.0.0 start /data/codes/antdesign/dva-boot-admin
> react-app-rewired start

/data/codes/antdesign/dva-boot-admin/node_modules/_react-app-rewire-less-modules@1.1.0@react-app-rewire-less-modules/index.js:25
  const { index, rules } = findIndexAndRules(rulesSource, ruleMatcher);
          ^

TypeError: Cannot destructure property `index` of 'undefined' or 'null'.
    at findRule (/data/codes/antdesign/dva-boot-admin/node_modules/_react-app-rewire-less-modules@1.1.0@react-app-rewire-less-modules/index.js:25:28)
    at /data/codes/antdesign/dva-boot-admin/node_modules/_react-app-rewire-less-modules@1.1.0@react-app-rewire-less-modules/index.js:60:37
    at Object.override [as webpack] (/data/codes/antdesign/dva-boot-admin/config-overrides.js:33:4)
    at Object.<anonymous> (/data/codes/antdesign/dva-boot-admin/node_modules/_react-app-rewired@1.6.2@react-app-rewired/scripts/start.js:13:13)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:742:12)
    at startup (internal/bootstrap/node.js:266:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:596:3)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! dva-boot-admin@1.0.0 start: `react-app-rewired start`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the dva-boot-admin@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2018-09-26T02_32_54_007Z-debug.log

 0 info it worked if it ends with ok
  2 1 verbose cli [ '/data/app/nodejs/node-v10.8.0-linux-x64/bin/node',
  3 1 verbose cli   '/data/app/nodejs/node-v10.8.0-linux-x64/lib/node_modules/cnpm/node_modules/.bin/npm',
  4 1 verbose cli   '--userconfig=/root/.cnpmrc',
  5 1 verbose cli   '--disturl=https://npm.taobao.org/mirrors/node',
  6 1 verbose cli   '--registry=https://registry.npm.taobao.org',
  7 1 verbose cli   'run',
  8 1 verbose cli   'start' ]
  9 2 info using npm@6.4.1
 10 3 info using node@v10.8.0
 11 4 verbose run-script [ 'prestart', 'start', 'poststart' ]
 12 5 info lifecycle dva-boot-admin@1.0.0~prestart: dva-boot-admin@1.0.0
 13 6 info lifecycle dva-boot-admin@1.0.0~start: dva-boot-admin@1.0.0
 14 7 verbose lifecycle dva-boot-admin@1.0.0~start: unsafe-perm in lifecycle true
 15 8 verbose lifecycle dva-boot-admin@1.0.0~start: PATH: /data/app/nodejs/node-v10.8.0-linux-x64/lib/node_modules/cnpm/node_mo    dules/npm/node_modules/npm-lifecycle/node-gyp-bin:/data/codes/antdesign/dva-boot-admin/node_modules/.bin:/data/app/nodejs/n    ode-v10.8.0-linux-x64/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/usr/local/go/bin:/root/bin
 16 9 verbose lifecycle dva-boot-admin@1.0.0~start: CWD: /data/codes/antdesign/dva-boot-admin
 17 10 silly lifecycle dva-boot-admin@1.0.0~start: Args: [ '-c', 'react-app-rewired start' ]
 18 11 silly lifecycle dva-boot-admin@1.0.0~start: Returned: code: 1  signal: null
 19 12 info lifecycle dva-boot-admin@1.0.0~start: Failed to exec start script
 20 13 verbose stack Error: dva-boot-admin@1.0.0 start: `react-app-rewired start`
 21 13 verbose stack Exit status 1
 22 13 verbose stack     at EventEmitter.<anonymous> (/data/app/nodejs/node-v10.8.0-linux-x64/lib/node_modules/cnpm/node_module    s/npm/node_modules/npm-lifecycle/index.js:301:16)
 23 13 verbose stack     at EventEmitter.emit (events.js:182:13)
 24 13 verbose stack     at ChildProcess.<anonymous> (/data/app/nodejs/node-v10.8.0-linux-x64/lib/node_modules/cnpm/node_module    s/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
 25 13 verbose stack     at ChildProcess.emit (events.js:182:13)
 26 13 verbose stack     at maybeClose (internal/child_process.js:962:16)
 27 13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:249:5)
 28 14 verbose pkgid dva-boot-admin@1.0.0
 29 15 verbose cwd /data/codes/antdesign/dva-boot-admin
30 16 verbose Linux 4.17.0-1.el7.elrepo.x86_64
 31 17 verbose argv "/data/app/nodejs/node-v10.8.0-linux-x64/bin/node" "/data/app/nodejs/node-v10.8.0-linux-x64/lib/node_module    s/cnpm/node_modules/.bin/npm" "--userconfig=/root/.cnpmrc" "--disturl=https://npm.taobao.org/mirrors/node" "--registry=http    s://registry.npm.taobao.org" "run" "start"
 32 18 verbose node v10.8.0
 33 19 verbose npm  v6.4.1
 34 20 error code ELIFECYCLE
 35 21 error errno 1
 36 22 error dva-boot-admin@1.0.0 start: `react-app-rewired start`
 37 22 error Exit status 1
 38 23 error Failed at the dva-boot-admin@1.0.0 start script.
 39 23 error This is probably not a problem with npm. There is likely additional logging output above.
 40 24 verbose exit [ 1, true ]

**Comment by weiq** [comment]
用yarn代替cnpm
