### ISSUE TITLE
ie10下运行报错

### ISSUE THREAD

**Issue by liuguoxionglang** [LANIF-UI/dva-boot-admin#19]
调试窗口报错
function _classCallCheck(instance, Constructor) {
  if (!(instance instanceof Constructor)) {
    throw new TypeError("Cannot call a class as a function");  //此处跑出错误 
  }
}
控制台报错
Warning: The <DynamicComponent /> component appears to have a render method, but doesn't extend React.Component. This is likely to cause errors. Change DynamicComponent to extend React.Component instead.
SCRIPT5022: 引发了异常但未捕获

**Comment by weiq** [comment]
暂时没测试过ie10，是否是babel-polyfill的问题
