### ISSUE TITLE
能不能实现左侧是个树状菜单，右侧是个table,可以进行增删改查的功能？

### ISSUE THREAD

**Issue by dongjunwen** [LANIF-UI/dva-boot-admin#2]
如题，点击左侧树状菜单。右侧table可以动态刷新，父节点和子节点，有上下级关系

**Comment by weiq** [comment]
@dongjunwen 刚才把这个例子放到DataTable的Demo页面了 https://github.com/LANIF-UI/dva-boot-admin/blob/master/src/routes/Widgets/DataTable/components/index.js#L160
