### ISSUE TITLE
sidebar中Link a标签字体颜色问题

### ISSUE THREAD

**Issue by johnnylc** [LANIF-UI/dva-boot-admin#25]
当使用light或者gray侧边栏皮肤时，存在两个问题：
1，单级menu和submenu的字体颜色存在区别
<img width="242" alt="differencolor" src="https://user-images.githubusercontent.com/12717523/48847372-546fc800-eddc-11e8-8685-facb29d4db76.png">
2，清空缓存初次开启页面时，在sidebar collapse状态下未加载标签的hover tooltip颜色异常
<img width="198" alt="unnormal" src="https://user-images.githubusercontent.com/12717523/48847440-85e89380-eddc-11e8-89f6-fd5be79232ec.png">

经调试发现样式被assets/index.less中的a标签相关样式覆盖
<img width="394" alt="fix" src="https://user-images.githubusercontent.com/12717523/48847683-1aeb8c80-eddd-11e8-8940-648ef98638bb.png">

注释以上样式代码中
a,
a:link {
  text-decoration: none;
  color: #333;
}
可修复，不确定是否会影响框架其他功能

**Comment by johnnylc** [comment]
后发现注释掉 color: #333; 就可以了

**Comment by weiq** [comment]
第二个问题，我本地是这样的
![111](https://user-images.githubusercontent.com/1697158/48875488-506f9480-ee34-11e8-99ca-8fb53cea7bfe.gif)

**Comment by weiq** [comment]
第一个问题
a,
a:link {
text-decoration: none;
color: #333;
}
这些样式是为了覆盖antd的a标签样式，这块我在改一下

**Comment by weiq** [comment]
@johnnylc 已修复

**Comment by johnnylc** [comment]
测试没问题 感谢！
