### ISSUE TITLE
windows系统下跑不起来

### ISSUE THREAD

**Issue by Mathround** [LANIF-UI/dva-boot-admin#27]
`E:\dva-boot-admin-master\node_modules\_react-app-rewire-less-modules@1.1.0@react-app-rewire-less-modules\index.js:25
  const { index, rules } = findIndexAndRules(rulesSource, ruleMatcher);
          ^

TypeError: Cannot destructure property `index` of 'undefined' or 'null'.
    at findRule (E:\dva-boot-admin-master\node_modules\_react-app-rewire-less-modules@1.1.0@react-app-rewire-less-modules\index.js:25:28)
`

**Comment by weiq** [comment]
重复 https://github.com/LANIF-UI/dva-boot-admin/issues/18

**Comment by Mathround** [comment]
> 重复 #18

原来如此 ...已经用yarn正常跑起来了

**Comment by Mathround** [comment]
> 重复 #18

不支持热更新？我每次做修改完后会把我整个页面重新加载一遍
