### ISSUE TITLE
yarn 报错

### ISSUE THREAD

**Issue by 363676727** [LANIF-UI/dva-boot-admin#28]
node v10.10.0
yarn v1.9.2

![image](https://user-images.githubusercontent.com/29798215/49924798-199c1400-fef2-11e8-9af1-8578c853e256.png)

**Comment by weiq** [comment]
把yarn换成国内镜像，在用安一下试试

**Comment by 363676727** [comment]
@weiq 换了也不行
![image](https://user-images.githubusercontent.com/29798215/49990934-6a773f80-ffba-11e8-92ec-4fe01a5bba9c.png)

**Comment by 363676727** [comment]
@363676727 fsevents这个好像是文件监听类似的包

**Comment by weiq** [comment]
![image](https://user-images.githubusercontent.com/1697158/49992172-3bfb6380-ffbe-11e8-99b2-dc33edc1fb62.png)
刚才我又升级了我的node和yarn到最新版重安了一遍都过了

**Comment by 363676727** [comment]
@weiq 你的node版本是?

**Comment by weiq** [comment]
v10.14.2

**Comment by 363676727** [comment]
https://github.com/yarnpkg/yarn/issues/3678

**Comment by weiq** [comment]
:+1: 看起来像是同样的问题
