### ISSUE TITLE
服务器回传JSON格式

### ISSUE THREAD

**Issue by leotang5451** [LANIF-UI/dva-boot-admin#29]
如果分页表格要使用真实数据，JSON要如何写

**Comment by weiq** [comment]
可以参考[CRUD](https://lanif-ui.github.io/dva-boot-admin/#/dva-boot-admin/crud)这个例子 打印一下反回数据, [配置](https://github.com/LANIF-UI/dva-boot-admin/blob/master/docs/config.md)

**Comment by leotang5451** [comment]
如果要处理到跨域的问题，以下是我的代码
   dispatch({
      type: 'userInfo/@request',
      payload: {
        valueField: 'httpbin',
        url: 'http://localhost:8080/Api/Management/GroupSet',
        method: 'GET',
      }
    });
有指定使用GET，不过Request的却是OPTIONS是还有那边没设定到吗？

**Comment by weiq** [comment]
跨域如果是复杂请求的话是会有两条请求的，第一条是options，第二条是真实请求
https://github.com/LANIF-UI/dva-boot-admin/blob/master/docs/faqs.md#%E4%B8%8D%E9%85%8D%E4%BB%A3%E7%90%86%E5%90%8E%E5%8F%B0%E9%85%8D%E8%B7%A8%E5%9F%9F%E4%B8%8D%E6%8E%A8%E8%8D%90

**Comment by leotang5451** [comment]
解决了，感谢

**Comment by leotang5451** [comment]
请问在CRUD做修改时要如何做呢，例子里面是空的

 handleUpdate = () => {};

**Comment by weiq** [comment]
那个方法没用上，修改时走的是BaseComponent里的onUpload方法

**Comment by leotang5451** [comment]
已解决，感谢
