### ISSUE TITLE
表单那块选择角色类型,滑动页面,角色类型里面的数据会一直浮动

### ISSUE THREAD

**Issue by lijiahuide** [LANIF-UI/dva-boot-admin#3]

**Comment by weiq** [comment]
看到这个问题了，原因是antd的弹窗默认是绑定到body上的，而滑动的是内部容器，[#9072](https://github.com/ant-design/ant-design/issues/9072)，下一次提交我会默认把弹窗绑定到父级上

**Comment by lijiahuide** [comment]
好的,这个项目会坚持维护吗

**Comment by weiq** [comment]
@lijiahuide 会的，放心
