### ISSUE TITLE
有关标签页的问题

### ISSUE THREAD

**Issue by sillyfeng** [LANIF-UI/dva-boot-admin#31]
老铁好，
我看现在的标签页是记录了打开的**routeDate**， 但是每次点击的时候他都会重新render，页面上的内容是记录不了的，这样子不也就失去了标签页的意义了么。
不知道是不是我理解的有问题，目前是这样子吗？可以进行调整吗？

**Comment by weiq** [comment]
现在有两种方案：

一种是使用修改的route方案，比如[react-router-cache-route](https://github.com/CJY0208/react-router-cache-route)，替换一下程序中的路由

另一种是把程序中的所有装态都放到model里，用redux来保存状态，可参考[CRUD的model](https://github.com/LANIF-UI/dva-boot-admin/blob/master/src/routes/Business/CRUD/model/index.js#L8)，原理是只在第一次加载时请求数据，之后进行切换时，不会主动加载
