### ISSUE TITLE
[bug] 连续yield @request 并非是串行的

### ISSUE THREAD

**Issue by chenwangji** [LANIF-UI/dva-boot-admin#33]
感谢提供这么好的项目。
开发中遇到问题求解决，我在一个 effect 中连续用 @request, 但是并不能到等上一个回调后再执行下一个的效果。我自己写的 effect 可以实现，但是没有 @request 方便。
![qq20190221-111716](https://user-images.githubusercontent.com/23144765/53141332-a6d2a780-35ca-11e9-9748-5f18d95d377b.png)
![qq20190221-111418](https://user-images.githubusercontent.com/23144765/53141389-ded9ea80-35ca-11e9-91e7-3f91c3d47dd8.png)
![qq20190221-111455](https://user-images.githubusercontent.com/23144765/53141391-e1d4db00-35ca-11e9-8b89-18275612b28a.png)

**Comment by weiq** [comment]
@chenwangji 本身put就是异步的，所以不会阻塞，你的这个需求可以用`take`来解决
```js
*save({ payload }, { call, put, select, take }) {
      const { values, success } = payload;
      const { pageData } = yield select(state => state.crud);
      yield put({
        type: '@request',
        payload: {
          notice: true,
          url: '/crud/save',
          data: values
        }
      });
      // 等待@request结束
      yield take('@request/@@end');
      yield put({
        type: 'getPageInfo',
        payload: { pageData }
      });
      success();
    }
```

**Comment by chenwangji** [comment]
感谢！
可以再问个问题吗，我如何拿到 @request 之后，从后端返回的数据，类似于
```javascript
const res =  yield put({
    type: '@request',
    payload: {
      url: '/admin/userManage/deleteUserInfo',
      data: {
        id: records.map(item => item.rowKey)[0]
      },
      success
    }
})

yield take('@request/@@end')

if (res) {
   yield put({
        type: 'getPageInfo',
        payload: { pageData }
    }) 
}

```

**Comment by weiq** [comment]
使用 yield select()

**Comment by chenwangji** [comment]
select 是不是只能获取到 state 中的值啊，但是我有些请求并不会把返回结果存到 state, 那样用 select 就拿不到了

**Comment by weiq** [comment]
不放到state里 select 是取不到的，但是应该有变通的办法吧，是不是可以换个思路来考虑问题
