### ISSUE TITLE
缺少i18n国际化，希望能加入react-intl-universal进行国际化

### ISSUE THREAD

**Issue by UpliftingJie** [LANIF-UI/dva-boot-admin#34]
我找到一个dvajs结合react-intl进行国际化的demo，但react-intl听说存在很致命的问题，不建议使用。dvajs官方都没国际化的例子，刚刚接触dvajs这个东西，完全不知道国际化初始化应该放在哪。最近折腾这个，找到了初始化位置，在模块加载时引入国际化app.model(require('../models/i18n').default); 打算在项目中练练手，没找到比较好的demo，还是搞不出来。所以希望能加入react-intl-universal进行国际化。

**Comment by weiq** [comment]
感谢建议，现在事情太多，后期会考虑加入
