### ISSUE TITLE
手机模式下class="antui-icon ad ad-into"的按钮建议不显示

### ISSUE THREAD

**Issue by LifeIsABoat** [LANIF-UI/dva-boot-admin#36]
手机模式下class="antui-icon ad ad-into"的按钮建议不显示，会导致页面显示错乱

**Comment by weiq** [comment]
小屏时使用Drawer组件 https://github.com/LANIF-UI/dva-boot-admin/commit/a71eb8e658349f8cbd0aedac089e120203c703d8
