### ISSUE TITLE
关于request

### ISSUE THREAD

**Issue by c-yyy** [LANIF-UI/dva-boot-admin#38]
![image](https://user-images.githubusercontent.com/20608808/53773628-1b400b80-3f26-11e9-912b-67a309376331.png)
没找到在哪里改请求域名host

**Comment by weiq** [comment]
首先，针对这个url来说，因为没有接口，前台通过mock生成数据，具体Mock看下src/__mock__/user.js，这个登录api在Login下的service里，再者开发时推荐使用代理来发请求，这样可以解决跨域问题，具体配置在src/setupProxy.js

发请求时，首先会在mock的列表里看是不是mock接口，如果没找到就直接发请求，如果有代理会经过代理

**Comment by c-yyy** [comment]
这个代理里面写的接口怎么用到login下service里面呢，如果我的接口名字和mock里面的一样咋办
![image](https://user-images.githubusercontent.com/20608808/53780643-4df6fd80-3f40-11e9-8f8f-0272fd205f05.png)

**Comment by weiq** [comment]
本来真实的接口地址就要和mock的一样才有意义，如果相切换的话只要注释一下这个接口就可以了，一样的话优先走mock的

**Comment by ntuwang** [comment]
@weiq /user/menu这一部分能否不使用mock，直接写到问价里面？或者说有没有办法把mock 全拿掉，我不用mock，我是前后端都自己写，所以不用mock

**Comment by weiq** [comment]
可以啊，你把这部分的代码注释掉就可以了，或者直接在index.js里去掉mock支持
