### ISSUE TITLE
IE11报错，无法显示

### ISSUE THREAD

**Issue by guoweizhong** [LANIF-UI/dva-boot-admin#39]
最新版2019-3-5 ，IE11报错，无法显示 Symbol(Symbol.iterator)_8.yc9tcc9ua9w

**Comment by weiq** [comment]
感谢反馈，应该是升级了fetch-mock引起的 [fetch-mock](https://github.com/wheresrhys/fetch-mock/issues/415)，我还原回之前的版本了
![image](https://user-images.githubusercontent.com/1697158/53807574-e31ee400-3f8a-11e9-95e8-677b5633355a.png)
