### ISSUE TITLE
引入 bootstrap css问题

### ISSUE THREAD

**Issue by ntuwang** [LANIF-UI/dva-boot-admin#41]
Hi
我一引入bootstrap.css整个布局就乱掉了，Content组件貌似就不起作用了，你们引入bootstrap会有问题吗

**Comment by ntuwang** [comment]
bootstrap3和4都会有问题

**Comment by weiq** [comment]
应该是冲突了，比如都有container或都有nav

**Comment by ntuwang** [comment]
> 应该是冲突了，比如都有container或都有nav

那有办法解决吗？

**Comment by weiq** [comment]
引入前想好为什么要重新引入一套规则，看看是不是必需的，引入后必然体积会增大，如果确实要引入可以看看这个文章https://stackoverflow.com/questions/18092310/legacy-css-conflicts-with-bootstrap-how-to-resolve

**Comment by ntuwang** [comment]
> 引入前想好为什么要重新引入一套规则，看看是不是必需的，引入后必然体积会增大，如果确实要引入可以看看这个文章https://stackoverflow.com/questions/18092310/legacy-css-conflicts-with-bootstrap-how-to-resolve

因为我是后端不是前端，很多组件都是网上抄的，有的要依赖bootstrap.css，所以就尝试着发现了这个问题

**Comment by weiq** [comment]
好的，你可以试下
