### ISSUE TITLE
如何 优雅的拿掉mock

### ISSUE THREAD

**Issue by ntuwang** [LANIF-UI/dva-boot-admin#43]
Hi 大佬
我看到登录 /api/user/login 和菜单导航 /api/user/menu 是走mock，怎么才能把mock全部拿掉，特别是菜单导航，我是想写在js或者json文件里面的

**Comment by weiq** [comment]
![image](https://user-images.githubusercontent.com/1697158/54592826-1c198700-4a68-11e9-8e37-04fe5ad2d01f.png)

**Comment by ntuwang** [comment]
注释完之后 ，导航菜单该怎么写呢

**Comment by ntuwang** [comment]
![image](https://user-images.githubusercontent.com/11935122/54593283-2daf5e80-4a69-11e9-8fe1-87f4674e324d.png)
我尝试着去改global.js没成功 @weiq

**Comment by weiq** [comment]
走你真实的后台接口

**Comment by ntuwang** [comment]
> 走你真实的后台接口

可是 导航菜单  我是走接口的 ，想直接用js或者json文件去定义的
![image](https://user-images.githubusercontent.com/11935122/54593652-f5f4e680-4a69-11e9-9b1b-aa1e19cf5fc6.png)

**Comment by weiq** [comment]
没明白，只要按格式组装数据就可以了

**Comment by weiq** [comment]
没明白，只要按格式组装数据就可以了
