### ISSUE TITLE
能不能实现顶部菜单呢？

### ISSUE THREAD

**Issue by hphpwj** [LANIF-UI/dva-boot-admin#44]
能不能实现像AntDesignPro那样实现左侧菜单和顶部菜单自由切换的功能呢？
[https://preview.pro.ant.design/dashboard/analysis?layout=topmenu&contentWidth=Fixed&pwa=1](https://preview.pro.ant.design/dashboard/analysis?layout=topmenu&contentWidth=Fixed&pwa=1)

**Comment by weiq** [comment]
好的，先加到待办里吧
