### ISSUE TITLE
开发计划是否以后考虑Typescript化?

### ISSUE THREAD

**Issue by zzyyzz1992** [LANIF-UI/dva-boot-admin#47]
开发计划是否以后考虑Typescript化?
如ant pro一样.

**Comment by weiq** [comment]
嗯，完全切到ts的话工作量还是很大的 ant pro 现在的v4版就是ts的，现在好像还不建议使用，之后我们也可以分出来一个ts分支来做这块的事情，主要看用ts的人多少

**Comment by zzyyzz1992** [comment]
谢谢
