### ISSUE TITLE
请教下搜索问题

### ISSUE THREAD

**Issue by laiyiyi** [LANIF-UI/dva-boot-admin#48]
请教下，table搜索，怎么把搜索条件带到浏览器地址 ?a=**&b=**,用这种形式呢？

**Comment by weiq** [comment]
```
yield put({
        type: '@request',
        payload: {
          valueField: 'pageData',
          url: '/crud/getList',
          method: 'GET',
          pageInfo: pageData
        }
      });
```

**Comment by laiyiyi** [comment]
![image](https://user-images.githubusercontent.com/12541388/56027647-05094480-5d49-11e9-895a-424d9c4586cf.png)

**Comment by weiq** [comment]
这上面不会变啊，是异步请求啊，不是form提交

**Comment by laiyiyi** [comment]
这不是react-router的问题吗
![image](https://user-images.githubusercontent.com/12541388/56087936-3ea49180-5ea8-11e9-826a-8375ab64849a.png)
