### ISSUE TITLE
这个修改成多个标签页的好修改吗

### ISSUE THREAD

**Issue by lijiahuide** [LANIF-UI/dva-boot-admin#5]
这个修改成多个标签页的好修改吗

**Comment by weiq** [comment]
![image](https://user-images.githubusercontent.com/1697158/42353808-6d8e3082-80f5-11e8-8970-3fa2b6f3b33c.png)

**Comment by lijiahuide** [comment]
明白了 还有如果你这上面修复了一些问题，我本地的如何更新，是找到对应的文件自己手动修改吗？

**Comment by weiq** [comment]
@lijiahuide 你可以fork这个项目，之后通过merge进行合并啊，这方面的知识你可以google一下，比如“如何同步 Github fork 出来的分支”，之后我会提交一个标签布局的示例 :smile:

**Comment by lijiahuide** [comment]
👍好的 非常感谢！ lijiahuide 邮箱：lijiahuide@sina.cn 签名由 网易邮箱大师 定制 在2018年07月06日 09:53，魏小雨 写道： @lijiahuide 你可以fork这个项目，之后通过merge进行合并啊，这方面的知识你可以google一下，比如“如何同步 Github fork 出来的分支”，之后我会提交一个标签布局的示例 😄 — You are receiving this because you were mentioned. Reply to this email directly, view it on GitHub, or mute the thread.

**Comment by pedrobabo** [comment]
厉害厉害，我来学习下

**Comment by lijiahuide** [comment]
![image 1](https://user-images.githubusercontent.com/7847015/42451535-203f506e-83ba-11e8-8a8b-a76f61ffd123.png)
 这个伸缩之后右侧怎么是空白的，之前我记得是没有的

**Comment by weiq** [comment]
@lijiahuide 这个一直就有的，计划放一些控制类的功能或网站状态图表在右边栏的 😎
