### ISSUE TITLE
搞了半天这是个伪多标签。。。

### ISSUE THREAD

**Issue by gaoqiang19514** [LANIF-UI/dva-boot-admin#50]

**Comment by weiq** [comment]
什么是真多标签，有问题建议描述清晰，如果吐槽请加群

**Comment by gaoqiang19514** [comment]
切换一下状态全部重置了，这就是伪多标签

**Comment by gaoqiang19514** [comment]
切换一下状态全部重置了，这就是伪多标签

**Comment by weiq** [comment]
这和多标签没关系，是react-router切换时会重新渲染，相关问题参考#31，不要重复提问，还有觉得不好你可以不用，要不你自个实现一个你说的“真标签的”
