### ISSUE TITLE
希望增加可编辑table多记录批量提交

### ISSUE THREAD

**Issue by wysj1478** [LANIF-UI/dva-boot-admin#54]
谢谢能提供这么好的项目！

类似图上销售订单明细，全部明细记录输入好后，点击确认订单后，能将明细数据批量提交给后台
![image](https://user-images.githubusercontent.com/38254229/62603243-17c30d00-b928-11e9-85a9-ed20ca99e9fa.png)

另：autocomplete不能输入中文，输入的是字母，过去的版本没有这个问题。时间字段提交给后台是moment,每次提交要转换，希望能有个统一处理转换。Form表单不够紧凑，留白还是太多了，做一个像上面的订单界面感觉一页容不下。

**Comment by weiq** [comment]
https://github.com/LANIF-UI/dva-boot-admin/issues/15#issuecomment-473560128
可编辑现在是支持的
