### ISSUE TITLE
大佬，能添加个热更新吗？整体刷新加载有点慢哦

### ISSUE THREAD

**Issue by Willworkgogogo** [LANIF-UI/dva-boot-admin#6]

**Comment by weiq** [comment]
修改代码的时候支持热更新的啊
![image](https://user-images.githubusercontent.com/1697158/42870609-da6d45c6-8aaa-11e8-9415-e4cd83e3522d.png)

**Comment by Willworkgogogo** [comment]
我理解的热更新是使用了react-hot-loader类似的插件，通过webpack的hot功能替换更新的组件，而不是整个页面的刷新。我这个项目用到了热更新，可以参考下https://github.com/Willworkgogogo/react-frame
感谢大佬

**Comment by weiq** [comment]
啊，我想你说的是这个插件[react-app-rewire-hot-loader](https://github.com/cdharris/react-app-rewire-hot-loader)，按照这上面的说明应该可以很方便的增加这个功能，可以考虑晚些时候添加到工程中，我现在正在开发一个Ripple功能，你可以帮忙测试一下使用这个插件后会提升多少么 :smile:

**Comment by Willworkgogogo** [comment]
@weiq 多谢提点，我周末就尝试加入😄。 感谢你做了这么好的一个作品，加油哦，期待你的继续完善

**Comment by weiq** [comment]
先关闭了，如果有问题在打开
