### ISSUE TITLE
Please use `require("history").createHashHistory`

### ISSUE THREAD

**Issue by q264771003** [LANIF-UI/dva-boot-admin#60]
Warning: Please use `require("history").createHashHistory` instead of `require("history/createHashHistory")`. Support for the latter will be removed in the next major release.

使用dva创建的项目使用同样的方式为什么没有警告
import createHistory from 'history/createHashHistory';
const app = dva({
  history: createHistory({
    basename: ‘/’
  })
});

**Comment by weiq** [comment]
可能是history包版本问题吧，新版本不建议这么做了
