### ISSUE TITLE
Tab page切换会把原来输入的内容清空

### ISSUE THREAD

**Issue by GerryGe** [LANIF-UI/dva-boot-admin#64]
某个Tab page输入一些内容之后切换到另一个page，再返回原来的page会把输入的内容清空掉，请问怎么解决？

**Comment by weiq** [comment]
嗯这个tab切换其实是切换的路由，因为react-router不支持路由缓存功能，其它办法可以看https://github.com/LANIF-UI/dva-boot-admin/issues/31，

**Comment by GerryGe** [comment]
好的，感谢感谢
