### ISSUE TITLE
SearchBar和ModalForm的columns单独写各自的array，会报ID重名

### ISSUE THREAD

**Issue by niaonile** [LANIF-UI/dva-boot-admin#65]
[DOM] Found 3 elements with non-unique id #deptName。
提交表单和搜索项不一样

**Comment by weiq** [comment]
上代码片段看下，暂时没遇到过这种问题

**Comment by niaonile** [comment]
`export default (self, employees) => [
    {
        title: '数据源名称',
        name: 'deptName',
        tableItem: {},
        searchItem: {
            group: 'abc'
        },
        formItem: {
            rules: [
                {
                    required: true,
                    message: '请输入数据源名称',
                }
            ],
        }
    },
    {
        title: '数据源类型',
        name: 'distributionNetwork',
        dict: [{ code: '0', codeName: 'a' }, { code: '1', codeName: 'b' }],
        formItem: {
            type: 'select',
            rules: [
                {
                    required: true,
                    message: '请选择数据源类型',
                }
            ],
        },
    },
    {
        title: '驱动类',
        name: 'qd',
        dict: [{ code: '0', codeName: '驱动a' }, { code: '1', codeName: '驱动b' }],
        formItem: {
            type: 'select',
            rules: [
                {
                    required: true,
                    message: '请输入数据库用户名',
                }
            ],
        }
    },
    {
        title: '链接串',
        name: 'lj',
        formItem: {
            // disabled: true,
            rules: [
                {
                    required: true,
                    message: '请输入链接串',
                }
            ],
        }
    },
    {
        title: '数据库用户名',
        name: 'sqlName',
        formItem: {
            rules: [
                {
                    required: true,
                    message: '请输入数据库用户名',
                }
            ],
        }
    },
    {
        title: '数据库密码',
        name: 'sqlPwd',
        formItem: {
            type: 'password'
        }
    },
    {
        title: '操作',
        tableItem: {
            width: 180,
            render: (text, record) => (
                <DataTable.Oper>
                    <Button tooltip="修改" onClick={e => self.onUpdate(record)}>
                        <Icon type="edit" />
                    </Button>
                    <Button tooltip="删除" onClick={e => self.onDelete(record)}>
                        <Icon type="trash" />
                    </Button>
                    <Button tooltip="其他操作">
                        {/*<Link to={"/crud/detail?id=" + record.id}>*/}
                        <Icon type="link" antd />
                        {/*</Link>*/}
                    </Button>
                </DataTable.Oper>
            )
        }
    }
];`
columns是动过的，其余文件是按crud复制的

**Comment by weiq** [comment]
看这个没问题，每个id只有一个，不会重复啊
