### ISSUE TITLE
Loading.effects下状态在视图中始终为false

### ISSUE THREAD

**Issue by Deantsui** [LANIF-UI/dva-boot-admin#67]
输入：触发effect中的enhance
实际输出：connect连接的视图中Loading.effects对应的状态始终为false，redux调试工具中发现Loading.effects下状态有变化。
预期输出：connect连接的视图中Loading.effects与实际请求状态对应-

<sub>Sent from <a href="https://itunes.apple.com/cn/app/id1314212521">PPHub</a></sub>

**Comment by weiq** [comment]
是dva-loading这个没生效么，方便提供演示环境或者压缩包，我排查下问题

**Comment by Deantsui** [comment]
[components文件18、84行](https://github.com/Deantsui/dva-boot-admin/blob/x-fream-dev/src/routes/Setting/Role/components/index.js)
[model文件40行](https://github.com/Deantsui/dva-boot-admin/blob/x-fream-dev/src/routes/Setting/Role/model/index.js)
render中loading. effects内的enhance始终为false，感谢大佬 @weiq

**Comment by Deantsui** [comment]
因为有时数据结构复杂，需要优化分页返回的数据，所以在编辑里重新拉取一边数据，为了用户体验，在模态框里加了个loading，传入的loading. effects['xxx']结果发现这个值始终为false，然后打印出整个loading，发现loading.effects下面除了“@/request”其他值始终都为false

**Comment by weiq** [comment]
dva-loading只能异步请求有作用，因为你在组件dispatch一个getPageInfo没有真正发送请求，而是在model里又调用put的@request才是真正发送的请求，所以loading里只是role/@request才会改变

**Comment by Deantsui** [comment]
感谢，所以用dva-loading的话就，只能使用原始的写法不能使用modelEnhance了是吗，或者手动写loading

**Comment by weiq** [comment]
嗯，暂时是这样的，我在研究一下这块

**Comment by Deantsui** [comment]
好的，非常感谢。
