### ISSUE TITLE
能讲一下这个项目怎么和后台连接吗

### ISSUE THREAD

**Issue by dns180** [LANIF-UI/dva-boot-admin#68]
谢谢，

**Comment by dns180** [comment]
request.config(config.request);
console.log('this is request', request);
// 使用mock数据
require('./__mocks__');
// require('http://www.minhw.com');
// -> Developer mock data
// if (process.env.NODE_ENV === 'development') {
//   require('./__mocks__');
// }
// -------

注销掉require('./__mocks__');以后 直接登录也不能登录了。

**Comment by dns180** [comment]
连后台的话， 是require到setupProxy.js这个js文件吗

**Comment by dns180** [comment]
然后里面的参数配置 是参照// https://facebook.github.io/create-react-app/docs/proxying-api-requests-in-development#configuring-the-proxy-manually这个吗？？

**Comment by dns180** [comment]
如果我猜对了，那开发完以后。前端是要导出放到后到项目里面去的。。。这应该怎么配置呢，在不知道部署服务器IP 域名的情况。

**Comment by weiq** [comment]
1.在不知道ip和域名时可以使用[相对路径](https://github.com/LANIF-UI/dva-boot-admin/blob/master/docs/build.md#%E5%8F%91%E5%B8%83%E8%B7%AF%E5%BE%84)
2.代理是开发时使用的，打包后就没用了，有跨域问题可以使用nginx代理，或者直接请求后台地址（在一起的话可以直接用相对路径）
3.mock是为了在没有后台时独立开发用的，后台写好后直接注释对应接口就行，你说的登录不了，是不是把登录的mock接口注释了，[文档里有写](https://github.com/LANIF-UI/dva-boot-admin/blob/master/docs/mock.md#%E5%AF%B9%E6%8E%A5%E7%9B%B4%E5%AE%9E%E6%8E%A5%E5%8F%A3)
