### ISSUE TITLE
表单验证问题

### ISSUE THREAD

**Issue by ofirefish** [LANIF-UI/dva-boot-admin#70]
请问怎样把提交表单时服务端验证返回的错误信息，渲染到控件上？就像前端表单验证一样。

**Comment by weiq** [comment]
可以参考antd的form自定义验证的例子，把columns定义成函数形式，传入后台信息，例如

![image](https://user-images.githubusercontent.com/1697158/66714818-5379c780-edee-11e9-801f-d9935a15a7e9.png)
