### ISSUE TITLE
切换路由之后，一定要手动刷新 dva 里面的 subscriptions 才能监听到

### ISSUE THREAD

**Issue by Hericium** [LANIF-UI/dva-boot-admin#71]
> 切换路由之后，一定要手动刷新 dva 里面的 subscriptions 才能监听到
因为想把请求都放在model层，所有都用了无状态组件，引入了subscriptions，当location.pathname变化时，请求要初始化的接口，就不用在也没层去写ajax了。但是发现这个框架左侧菜单切换后，不能执行subscriptions里面的代码。

`
subscriptions: {

    setup ({ dispatch, history }) {
      history.listen((location) => {
        console.log(1)
        if (location.pathname === '/important-guest-report') {
          const payload = queryString.parse(location.search) || { page: 1, pageSize: 10 };
          dispatch({
            type: 'query',
            payload,
          });
        }
      });
    },
  },
`
![image](https://user-images.githubusercontent.com/26086540/66975107-f4f36880-f0cf-11e9-8c6c-8bb1d896cb88.png)
左侧路由切换后，subscriptions里面的代码不执行，执行的还是第一个加载的模块的代码，一定要说手动刷新，才能执行当前模块的代码。

**Comment by weiq** [comment]
不会啊，每次都会进的
![111](https://user-images.githubusercontent.com/1697158/66976614-16a31e80-f0d5-11e9-9e5c-8c7939de2db2.gif)
