### ISSUE TITLE
最新版在IE11报错不显示，在Edge显示不正常

### ISSUE THREAD

**Issue by guoweizhong** [LANIF-UI/dva-boot-admin#74]
最新版在IE11报错不显示，在Edge显示不正常，
SCRIPT438: 对象不支持“startsWith”属性或方法
index.js (48,1)
SCRIPT5009: “Promise”未定义
index.js (1603,9)

**Comment by weiq** [comment]
引入 babel-polyfill 试试

**Comment by dongkeng001** [comment]
> 最新版在IE11报错不显示，在Edge显示不正常，
> SCRIPT438: 对象不支持“startsWith”属性或方法
> index.js (48,1)
> SCRIPT5009: “Promise”未定义
> index.js (1603,9)



> 引入 babel-polyfill 试试

除了楼上上的这个问题，还有个问题就是登录输入框默认显示的账号和密码是没有居中的，也是IE上的问题

**Comment by weiq** [comment]
我用ie11看是正常的 @dongkeng001
