### ISSUE TITLE
固定一两列， 表格中间会出现大片空白将固定列和非固定列分开两处

### ISSUE THREAD

**Issue by linhuisheng** [LANIF-UI/dva-boot-admin#75]
{
    title: '单位名称',
    name: 'deptName',
    tableItem: {fixed: 'left'},
    searchItem: {
      group: 'abc'
    },
    formItem: {}
  },
![image](https://user-images.githubusercontent.com/8087304/70063048-21345b80-1622-11ea-99df-d4de04c06de0.png)

**Comment by weiq** [comment]
已解决 看表格固定列示例 https://github.com/LANIF-UI/dva-boot-admin/blob/master/src/routes/Widgets/DataTable/components/columns.js#L148
