### ISSUE TITLE
表单复选框初始值清空的问题

### ISSUE THREAD

**Issue by SenvenQi** [LANIF-UI/dva-boot-admin#76]
我按照你的代码写了一个表单的复选框，它在列表中所以它具有初始值，但是当我点击时，似乎触发了事件将它清空了  我不希望它发生 请问有什么方法吗  我看过checkbox.js 我不知道该如何去做

**Comment by weiq** [comment]
请附加示例代码，这么说我不清楚

**Comment by SenvenQi** [comment]
`{
    title: '单警装备',
    name: 'description',
    formItem: { 
      type: 'checkbox',
      style:{color:'red'}
     },
    dict: getSingleWearEquip.map(item=>{return {code:item.id, codeName: item.name}}),
  },`

这个是我的Columns 配置的复选框 ，它具有列表的属性description ，以逗号隔开的字符串("1,2,3,4,5")

Component的代码复用你的代码  未做修改 

问题：  如我现在选择的是 code 为 1，2，3，4，5的复选框   但是当我第一次点击复选框时  初始值就消失了， 能否取消这个第一次的判断事件  不要清空初始值  点选复选框 从第一次就开始追加或减少

[https://snippets.cacher.io/snippet/c33a890c45e0341aefab](url) 这个是column配置
[https://snippets.cacher.io/snippet/538bd6c5cb189a417b47](url) 这个是视图

**Comment by weiq** [comment]
> 以逗号隔开的字符串("1,2,3,4,5")

这个是record里description的值么，应该是传入一个数组吧[1,2,3,4,5]并且类型也需要一样
我本地测试没问题

**Comment by SenvenQi** [comment]
好的  谢谢
