### ISSUE TITLE
不知道是不是我方法不对还是其它，ico图标改了没反应

### ISSUE THREAD

**Issue by dongkeng001** [LANIF-UI/dva-boot-admin#77]
整个项目能找到ico格式的图片暂时在public文件目录找到一张，为了测试直接将favicon.ico图片删掉发现没效果，ico图标依旧还在。
在public文件目录下的index.html里面将这段注释也没用

`<link rel="shortcut icon" href="%PUBLIC_URL%/favicon.ico">`

请问这个在哪里改呢

![default](https://user-images.githubusercontent.com/20589684/70509096-d195e880-1b69-11ea-88cb-24cf7b1ddf25.png)

**Comment by weiq** [comment]
就是这个，没反应应该是缓存引起的
