### ISSUE TITLE
Table组件莫名多出一行 当我固定列时 样式错位

### ISSUE THREAD

**Issue by SenvenQi** [LANIF-UI/dva-boot-admin#78]
![image](https://user-images.githubusercontent.com/24808595/70785953-76acfd00-1dc6-11ea-9ac5-8320530d80ed.png)

![image](https://user-images.githubusercontent.com/24808595/70785989-8cbabd80-1dc6-11ea-94cf-340b484db547.png)

**Comment by SenvenQi** [comment]
看代码列 谢谢作者  好了

**Comment by SenvenQi** [comment]
好像 不行  你那个isScroll 只能设置为bool
![image](https://user-images.githubusercontent.com/24808595/70787883-a4944080-1dca-11ea-8c59-dee62fda4821.png)

**Comment by SenvenQi** [comment]
我将版本调整为 3.24 .1  依然留白

**Comment by weiq** [comment]
最新的DataTable支持Object类型 https://github.com/LANIF-UI/dva-boot-admin/blob/master/src/components/DataTable/DataTable.js#L50

**Comment by weiq** [comment]
我在表格的例子里增加了一个固定列的例子
```
const dataTableProps8 = {
      loading,
      columns: columns6,
      isScroll: { x: 666 }, // 需要设一个宽
      rowKey: 'id',
      dataItems: lessData,
      showNum: true
    };

```

**Comment by SenvenQi** [comment]
明白了 但是我要重新替换项目 我觉得不好 要是能将这些组建 打包到npm仓库 那将是好的👌 谢谢大大
