### ISSUE TITLE
页面假死，一直loading

### ISSUE THREAD

**Issue by Willworkgogogo** [LANIF-UI/dva-boot-admin#8]
![image](https://user-images.githubusercontent.com/20815934/42993407-dc2f9b22-8c3d-11e8-95f4-db48bd06488f.png)

**Comment by Willworkgogogo** [comment]
访问的是线上地址https://lanif-ui.github.io/dva-boot-admin/#/datatable
复现方式：长时间未操作页面，再点击路由的时候会出现这种情况，今天至少出现4次了，没次都得重新刷新页面

**Comment by weiq** [comment]
@Willworkgogogo 控制台报什么错，是否是由于缓存引起的，一般出现这种情况多是，多是缓存引起的，我这里看不你的更多信息

**Comment by Willworkgogogo** [comment]
刚看到一个错误，切换的时候才出现的
![image](https://user-images.githubusercontent.com/20815934/42993659-7f31415e-8c3e-11e8-8599-0c1d1c2f27b7.png)

**Comment by weiq** [comment]
@Willworkgogogo 最好在本地开发环境测试一下，一般没问题。这种情况有时是国内的网络环境造成的，原因大家都知道，每一个chunk都是按需加载的页面或资源，正常的话是不会出现这种问题的，放心
![image](https://user-images.githubusercontent.com/1697158/42993755-c77ae1fe-8c3e-11e8-99df-674d91d854a9.png)

**Comment by Willworkgogogo** [comment]
@weiq 本地还没遇到这个问题，听你这么一解释，放心多了😊
