### ISSUE TITLE
formItem 的类型是upload   并且设置了rules，编辑的时候有什么方法能跳过验证吗？

### ISSUE THREAD

**Issue by eleanors** [LANIF-UI/dva-boot-admin#80]

**Comment by weiq** [comment]
没明白，是新增时需要验证，修改时不需要？上一下代码看下吧

**Comment by eleanors** [comment]
> 没明白，是新增时需要验证，修改时不需要？上一下代码看下吧

是这个意思  还有个问题就是upload类型的在更新modal里没有预览  如果要更新也有点困难

**Comment by weiq** [comment]
columns可以写成函数形式，传入一个参数判断是新增还是修改，来决定是否应用rules

**Comment by eleanors** [comment]
> rules

OK  非常感谢  你这个项目节省我很多时间  整体结构也一直是我想的

**Comment by weiq** [comment]
不客气哈 :smile:
