### ISSUE TITLE
文件上传的组装FormData 有文档吗 ？

### ISSUE THREAD

**Issue by SenvenQi** [LANIF-UI/dva-boot-admin#82]
![image](https://user-images.githubusercontent.com/24808595/71166044-e02c8000-228c-11ea-80d6-b58e4ea18c4d.png)
这个我没看明白  该如何做  我去Antd的站点也看过  我用的asp.net mvc  后台请求中获取不到文件
![image](https://user-images.githubusercontent.com/24808595/71166141-0b16d400-228d-11ea-9bea-662fc4f50993.png)
![image](https://user-images.githubusercontent.com/24808595/71166155-12d67880-228d-11ea-8b82-7752992ede5f.png)

**Comment by weiq** [comment]
看起来没什么问题，报错了么

**Comment by SenvenQi** [comment]
我用官网的例子是可以的  但是我用你的  好像不行  我也没找到原因   reqeust 的Files 属性没有文件  很奇怪

**Comment by SenvenQi** [comment]
你的属性 传过去 只是个字符串  [Object object]

**Comment by SenvenQi** [comment]
但是  filelist 的值好像是有的  双向react-component 的from值  也是对的

**Comment by SenvenQi** [comment]
你可以用后台试试  我重复 了好几次  确保没有问题的情况下测试的
