### ISSUE TITLE
打扰了，二级联动，重新选择第一个，第二个怎么清空已经选择了的

### ISSUE THREAD

**Issue by yigerendehaotianqi** [LANIF-UI/dva-boot-admin#83]
![1](https://user-images.githubusercontent.com/38287273/71507603-0d49e580-28c0-11ea-85b1-d3e5a2506216.png)
![2](https://user-images.githubusercontent.com/38287273/71507604-0f13a900-28c0-11ea-9dc6-3fddf1cf1354.png)
![3](https://user-images.githubusercontent.com/38287273/71507607-10dd6c80-28c0-11ea-9cbc-40a8acbcdff7.png)

我先选择了山东--济南
然后重新选择北京仓库，第二个还是济南，怎么清除啊

**Comment by weiq** [comment]
清除可以到antd官网上看组件介绍，联动可以用Cascade组件这个来做啊
