### ISSUE TITLE
Server issue after install

### ISSUE THREAD

**Issue by sealabr** [LANIF-UI/dva-boot-admin#85]
Helo, I'm trying to install on aws ec2 instance.

after yarn start... my instace doesnt connect anymore and i need to restart.

![image](https://user-images.githubusercontent.com/21187479/73686857-90244400-46a7-11ea-9020-1bdb94e098ae.png)

My instance
Edit:
![image](https://user-images.githubusercontent.com/21187479/73687013-e1ccce80-46a7-11ea-9eb7-e7ac192afdd0.png)

I run those commands:
$ git clone https://github.com/LANIF-UI/dva-boot-admin.git
$ cd dva-boot-admin
$ yarn
$ yarn start

**Comment by weiq** [comment]
I used [customize-cra](https://github.com/arackaf/customize-cra) not eject to use CRA, currently  [customize-cra](https://github.com/arackaf/customize-cra) does not support the latest CRA, I am also looking at this https://github.com/arackaf/customize-cra/issues/134

**Comment by FabioYami** [comment]
ok thanks!

**Comment by sealabr** [comment]
okay, thanks!
