### ISSUE TITLE
怎么获取响应头

### ISSUE THREAD

**Issue by q264771003** [LANIF-UI/dva-boot-admin#86]
我整个报文传输都是加密的，我要根据响应头的参数，判断响应报文是否是密文，是密文的话就要解密

**Comment by weiq** [comment]
你是用框架自带的请求方法么，最好提供代码看一下

**Comment by q264771003** [comment]
我用的是dva-boot-admin里面的config.js，对响应进行拦截
afterResponse: response =&gt; {

    //我想在这里做解密，响应值不是每次都是密文，所以我想利用响应头进行判断是否是密文，可response是报文体，没头



  return response
},
来后我发现可以使用responseType参数 $$.post('/monitor/mytest.json', payload,{responseType:null})afterResponse: response =&gt; {
    //密文传输
    if(response instanceof  Response){
        return response.text().then(data =&gt;{
            console.log(data) //data就是密文，我在这里做解密
            return data
        })
    }else{ //明文传输        const {returnCode} = response.reply;
        if(returnCode.type == "S"){
          return  response.reply;
        }else{
            let message = returnCode.message == undefined ? "未知错误" : returnCode.message;
            throw new Error(message);
        }
    }


},
虽然解决了，难免以后还是会用到响应头，我看请求的时候都可以设置请求头，难道没有取响应头的吗




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"魏小雨"<notifications@github.com&gt;;
发送时间:&nbsp;2020年2月6日(星期四) 晚上6:51
收件人:&nbsp;"LANIF-UI/dva-boot-admin"<dva-boot-admin@noreply.github.com&gt;;
抄送:&nbsp;"冯刚"<264771003@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [LANIF-UI/dva-boot-admin] 怎么获取响应头 (#86)




你是用框架自带的请求方法么，最好提供代码看一下

**Comment by weiq** [comment]
嗯，框架里用的是包装过的fetch,返回结果如果有responseType的话，列如默认是json会自动做一次拆包，response.json()，这时候头就没有了，afterResponse就是取的处理过的这个值，你把responseType设为null就能取到原始的response

要不我在增加一个新的拦截方法可以取到未处理的response呢，你用这个方法代替afterResponse,你觉得呢

**Comment by q264771003** [comment]
modelEnhance的@request请求是否可以设置responseType:null，我发现我很多地方还是用的@request请求，@request可以直接在view层、mode层使用，不需要service层，我觉得挺方便的。


我主要是写java的，前端我都是看你的文档模仿着写的。有时候都是console.log()连蒙带猜写出来的




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"魏小雨"<notifications@github.com&gt;;
发送时间:&nbsp;2020年2月6日(星期四) 晚上9:37
收件人:&nbsp;"LANIF-UI/dva-boot-admin"<dva-boot-admin@noreply.github.com&gt;;
抄送:&nbsp;"冯刚"<264771003@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [LANIF-UI/dva-boot-admin] 怎么获取响应头 (#86)




嗯，框架里用的是包装过的fetch,返回结果如果有responseType的话，列如默认是json会自动做一次拆包，response.json()，这时候头就没有了，afterResponse就是取的处理过的这个值，你把responseType设为null就能取到原始的response
 
要不我在增加一个新的拦截方法可以取到未处理的response呢，你用这个方法代替afterResponse,你觉得呢

**Comment by weiq** [comment]
好的一会我升级一下 cmn-utils 我新加了一个方法 parseResponse 你可以在这个里面获取头处时业务。

**Comment by weiq** [comment]
cmn-utils 升级到1.0.10
config.js request里增加 parseResponse
```
// afterResponse 之前执行
    parseResponse: ((response, responseType) => {
        // 可以获取响应头，如果头内容不全或为空，可能需要查看后端与nginx的配置
        response.headers.forEach((v, k) => {
          console.log(`${k}:${v}`);
        });
        // 可以自已处理返回响应内容 
        return response.json();
    }),
```

**Comment by q264771003** [comment]
thank you！


另外我想问，如果我要在前端对报文进行加密传输，能做到吗？


$$.post('/monitor/login.json', {}); 这个方法的第二个参数是把js对象转化为json字符串吧，但是我想在这里传text/plain类型的密文到java后台


------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"魏小雨"<notifications@github.com&gt;;
发送时间:&nbsp;2020年2月7日(星期五) 中午1:15
收件人:&nbsp;"LANIF-UI/dva-boot-admin"<dva-boot-admin@noreply.github.com&gt;;
抄送:&nbsp;"冯刚"<264771003@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [LANIF-UI/dva-boot-admin] 怎么获取响应头 (#86)




cmn-utils 升级到1.0.10
 config.js request里增加 parseResponse
 // afterResponse 之前执行     parseResponse: ((response, responseType) =&gt; {         // 可以获取响应头，如果头内容不全或为空，可能需要查看后端与nginx的配置         response.headers.forEach((v, k) =&gt; {           console.log(`${k}:${v}`);         });         // 可以自已处理返回响应内容          return response.json();     }),

**Comment by weiq** [comment]
$$.post默认content-type是application/json所以会转成json字符串，即使转了也不影响你加密信息，你还可以自已选择用哪种请求方式，https://github.com/LANIF-UI/cmn-utils#request

**Comment by q264771003** [comment]
export async function login(payload) {
&nbsp; &nbsp; let aesKey = CryptoJS.enc.Base64.parse($$.store.session('aesKey'))


&nbsp; &nbsp; let encrypted&nbsp; = CryptoJS.AES.encrypt(JSON.stringify(payload), aesKey, {
&nbsp; &nbsp; &nbsp; &nbsp; mode: CryptoJS.mode.ECB,
&nbsp; &nbsp; &nbsp; &nbsp; padding: CryptoJS.pad.Pkcs7
&nbsp; &nbsp; });


&nbsp; &nbsp; //使用这个方法请求，会对请求的报文加上双引号，"K2/VLo/yJXZR3QwOmq0hcfsI9nPwfLCLypd7NpYJca/Lt6O1PEx3KiSVjyF+9c3l"
&nbsp; &nbsp; return $$.post('/monitor/login.json', encrypted.toString());&nbsp;&nbsp;


&nbsp; &nbsp; //加上自定义请求头，就不会出现双引号号，K2/VLo/yJXZR3QwOmq0hcfsI9nPwfLCLypd7NpYJca/Lt6O1PEx3KiSVjyF+9c3l
&nbsp; &nbsp; return $$.post('/monitor/login.json', encrypted.toString(),{
&nbsp; &nbsp; &nbsp; &nbsp; headers: {
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; 'content-type': 'text/plain'
&nbsp; &nbsp; &nbsp; &nbsp; },
&nbsp; &nbsp; });



&nbsp; &nbsp; //最终我还是选择使用带双引号的，我发现带不带双引号，java AES都可以解密，但是如果把请求头换成了text/plain，后台框架不能把报文体解析成多个参数值，这样我还得去改造后台
}





------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"魏小雨"<notifications@github.com&gt;;
发送时间:&nbsp;2020年2月8日(星期六) 中午1:28
收件人:&nbsp;"LANIF-UI/dva-boot-admin"<dva-boot-admin@noreply.github.com&gt;;
抄送:&nbsp;"冯刚"<264771003@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [LANIF-UI/dva-boot-admin] 怎么获取响应头 (#86)




$$.post默认content-type是application/json所以会转成json字符串，即使转了也不影响你加密信息，你还可以自已选择用哪种请求方式，https://github.com/LANIF-UI/cmn-utils#request

**Comment by weiq** [comment]
对啊，因为application/json会把发送数据转成json字符串就会带双引号,你后台要是当成普通参数接受就会多出一个双引号
$$.postform(url, {data: 密码}) 加一个key,后台用data收，或者$$.post(url, {data: 密码}) 后台用Map或实体收，或者像你那么写都行

**Comment by q264771003** [comment]
呵呵，我的目的是整个报文体一个明文都没有，我的后台框架也是有拦截器的，请求、响应拦截，都是无感知的，自动判断是否加解密，如果请求资源在解密列表内就对报文进行解密，如果响应资源在加密列表内就对响应报文进行加密。这样不会改变我controller层已经定义好的方法和参数


npm down下来的cmn-utils是1.0.9的，没有1.0.10




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"魏小雨"<notifications@github.com&gt;;
发送时间:&nbsp;2020年2月8日(星期六) 晚上7:29
收件人:&nbsp;"LANIF-UI/dva-boot-admin"<dva-boot-admin@noreply.github.com&gt;;
抄送:&nbsp;"冯刚"<264771003@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [LANIF-UI/dva-boot-admin] 怎么获取响应头 (#86)




对啊，因为application/json会把发送数据转成json字符串就会带双引号,你后台要是当成普通参数接受就会多出一个双引号
 $$.postform(url, {data: 密码}) 加一个key,后台用data收，或者$$.post(url, {data: 密码}) 后台用Map或实体收，或者像你那么写都行

**Comment by weiq** [comment]
好了，我手动同步过来了，淘宝镜像最近不知道怎么了，同步很慢

**Comment by q264771003** [comment]
ok，可用，帮大忙了！这样即使没有https，也提高了安全级别。就是不知道中间人攻击是否可以拿到store里面的秘钥，另外想知道js 定义的变量能够被抓取到吗？例如：const clientPrivateKey = key.exportKey("private");&nbsp; //这是rsa算法动态生成的私钥，我不做任何输出，黑客能拿到吗？



&nbsp;parseResponse: ((response, responseType) =&gt; {
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; if(response.headers.get("encrypted") == "true"){
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; return response.text().then(data =&gt;{
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; let key = CryptoJS.enc.Base64.parse(store.session('aesKey'));
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; let decrypted&nbsp; = CryptoJS.AES.decrypt(data, key, {
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; mode: CryptoJS.mode.ECB,
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; padding: CryptoJS.pad.Pkcs7
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; });
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; const body = JSON.parse(decrypted.toString(CryptoJS.enc.Utf8));
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; return&nbsp; body;
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; })
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; }else{
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; return response.json();
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; }
&nbsp; &nbsp; &nbsp; }),



afterResponse: response =&gt; {


&nbsp; &nbsp; &nbsp; &nbsp; const {returnCode} = response.reply;
&nbsp; &nbsp; &nbsp; &nbsp; if(returnCode.type == "S"){
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; return&nbsp; response.reply;
&nbsp; &nbsp; &nbsp; &nbsp; }else{
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; let message = returnCode.message == undefined ? "未知错误" : returnCode.message;
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; throw new Error(message);
&nbsp; &nbsp; &nbsp; &nbsp; }
&nbsp; &nbsp; },









------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"魏小雨"<notifications@github.com&gt;;
发送时间:&nbsp;2020年2月8日(星期六) 晚上9:46
收件人:&nbsp;"LANIF-UI/dva-boot-admin"<dva-boot-admin@noreply.github.com&gt;;
抄送:&nbsp;"冯刚"<264771003@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [LANIF-UI/dva-boot-admin] 怎么获取响应头 (#86)




好了，我手动同步过来了，淘宝镜像最近不知道怎么了，同步很慢

**Comment by weiq** [comment]
前台的东西，肯定可以获取到
