### ISSUE TITLE
columns

### ISSUE THREAD

**Issue by ALicees** [LANIF-UI/dva-boot-admin#9]
您好，如何在columns.js 里表单上绑定任意一种event，比如说，我要跟一表单添加onfocus事件弹出一个modal框。 如果绑定成功，这个modal框组件写哪里，如何引用

**Comment by weiq** [comment]
columns里的formItem是直接用的antd里的对应组件 比如默认 `formItem: {}` 这样写用的就是 `Input`组件‘formItem: { type: 'select' }’就是下拉组件，要写事件的话直接在formItem里定义就行了,例：
```js
{
    title: '角色名',
    name: 'roleName',
    formItem: {
      onKeyDown: e => console.log(e)
    }
}
```

**Comment by weiq** [comment]
modal组件写到component里，使用self.openModal方式打开，参照 crud 示例的列表操作按钮的写法
