### ISSUE TITLE
路由问题

### ISSUE THREAD

**Issue by zjp123** [LANIF-UI/dva-boot-admin#92]
我在我的项目中，参照项目里面路由配置，然而页面上却不显示路由对应下的组件，请问这个路由配置方面，有什么注意事项吗

**Comment by weiq** [comment]
可以参考这个来做
https://github.com/LANIF-UI/dva-boot-admin/blob/master/docs/start.md#%E6%96%B0%E5%BB%BA%E4%B8%80%E4%B8%AA%E9%A1%B5%E9%9D%A2
